### ISSUE TITLE
Exercise 1 - How Do We Split Expenses?

### ISSUE THREAD

**Issue by snasirca** [nayema/domain-modeling-exercises#1]
There are `x` number of users who have spent a variable amount during a trip.

How might we determine who owes how much to whom? What steps would it entail?

**Comment by nayema** [comment]
## Splitting Expenses

**Declare** a _String array_ to hold each user's name. Call it _name_. 
**Declare** a _double array_ to hold the amount each user spent during the trip. Call it _amountSpent_.

**Declare** an _averageAmount()_ method that calculates the average amount spent by the total number of users.
1. **Get** total amount of users.
1. **Get** users _amountSpent_
    - Repeat with each user
1. **Calculate** the average of _amountSpent_

**Declare** an _balance()_ method that subtracts _averageAmount()_ with each users' _amountSpent_
1.**Repeat** for each user
1. **IF** the user's balance is < the _averageAmount_, _Print_ balance in currency format, owing to user with the highest balance
1. **IF** the user's balance is > the _averageAmount_, _Print_ receiving amount in currency format, to be received from user's or users' with negative balance(s)

**Comment by snasirca** [comment]
## Good:

Your algorithm for determining who owes how much is correct.

## Improve:

You can simplify the problem a bit by using a data structure that holds key value pairs. The key can be the name of the user and value can be the amount that they spent. Here is how such a thing is declared and used in Java:

```java
HashMap<String, double> amountsSpentForUsers = new HashMap<String, double>();
      
// Adding elements to HashMap
amountsSpentForUsers.put("Rakesh", 12.59);
amountsSpentForUsers.put("Rajeeb", 21.25);
amountsSpentForUsers.put("Ramal", 39.87);
```

## Overall:

Looks good. Very clear instructions that can be followed. Demonstrates clear thinking.
